### ISSUE TITLE
Failing taxonomy test

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1700] opened 2019-03-09 17:57 UTC
```
#   Failed test at t/tags.t line 289.
#     Structures begin differing at:
#          $got->[3] = 'en:salt'
#     $expected->[3] = 'en:orange'
# [
#   'en:fruit',
#   'en:citrus-fruit',
#   'en:fruit-juice',
#   'en:salt',
#   'en:sugar',
#   'en:orange',
#   'en:concentrated-orange-juice',
#   'en:orange-juice'
# ]
# Looks like you failed 1 test of 33.
```

**Comment by stephanegigandet** [comment] 2019-03-28 09:16
Duplicate of #1727

**Closed by stephanegigandet** 2019-03-28 09:16 UTC
Labels: bug, taxonomies
