### ISSUE TITLE
Add support for PDF images sent by producers

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#6587] opened 2022-04-11 10:02 UTC
### What

- Some producers link to PDF files in their GS1 product sheets. We currently do not support them (it results in a broken image).

### Proposed solution

Add some support for PDF files. e.g. convert to PNG, and keep original file.

### Part of
- #5521

**Comment by stephanegigandet** [comment] 2022-04-11 11:55
The current code seems to be trying to process pdf, there's a ghostscript process being created (that takes quite a bit of cpu)
  7671 off       20   0  145524  37320  10740 R  99.3  0.1   0:06.13 gs

**Comment by alexgarel** [comment] 2022-04-14 09:13
It seems to me that ImageMagick knows how to transform pdfs to jpeg (at least with the convert command line, it works fine).

In the code, you spoke about the problem that some images are not images but catalog or so. Maybe we could see how many pages there are in the PDF before importing (and maybe also how much text vs images to place thresholds ?)

I don't know if there are good PDF parsing library in perl. In python I know them, and as I worked a lot with PDF I know you need a strong one, because most PDF do not follow the specifications. 
Poppler might be a good candidate : https://metacpan.org/pod/Poppler

**Comment by stephanegigandet** [comment] 2022-04-15 10:38
The commit referenced just above removes the processing of PDF files, so that it doesn't result in broken images. As a result, it also speeds up imports that link to PDF files a lot.

Some of those PDFs are multi page documents (e.g. organic certification reports), those should not be turned into images.

**Comment by teolemon** [comment] 2022-07-21 11:50
- Dupe of #4993

**Closed** 2022-11-21 15:49 UTC
Labels: feature, producers platform
