### ISSUE TITLE
"Yes" doesn't shown in robotoff question (for some resolutions/zoom levels)

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#1788] opened 2019-05-20 10:07 UTC
Every page where a robotoff question is displayed at the end of the screen, the "yes" button is not shown: 
![image](https://user-images.githubusercontent.com/562352/58013428-e1c77700-7af6-11e9-9dbc-a705f41bb65f.png)

A quick and dirty fix is to change: `width: 80%;` in `:host { background-color: #274477; color: white; position: fixed; bottom: 0; width: 100%; border-top: 1px solid #eee; z-index: 100; padding-top: 10px; }`
(File: https://github.com/openfoodfacts/openfoodfacts-server/blob/a8dc903cb32c15288ff80aef079c92e3ee6f71d5/html/js/display-product.js )

@hangy?

**Comment by aleene** [comment] 2019-05-20 14:09
I do not even see the no! The width of the window does not seem to be taken into account.

**Comment by hangy** [comment] 2019-05-20 14:09
Can you give me some input on used OS, browser, and screen size? It worked successfully for me (with Chrome @ 1920x1080) on the weekend.

**Comment by CharlesNepote** [comment] 2019-05-20 14:41
I use both Firefox 66 (last version) and Chromium Version 73.0.3683.86 (Build officiel) under Linux Ubuntu 18.04 @ screen resolution 1920x1080. The "yes" button *never* appear.

Here is a screenshot under Chromium:
![Capture d’écran_2019-05-20_16-38-00](https://user-images.githubusercontent.com/562352/58029829-b0ae6d00-7b1d-11e9-9aba-2162d89885ce.png)

If I use 90% zoom, the "yes" button appear.

**Comment by aleene** [comment] 2019-05-20 20:05
This is the same as #1287, I guess. I use Safari on iMac and iPad.

**Comment by hangy** [comment] 2019-05-20 22:03
> I use both Firefox 66 (last version) and Chromium Version 73.0.3683.86 (Build officiel) under Linux Ubuntu 18.04 @ screen resolution 1920x1080. The "yes" button _never_ appear.
> 
> Here is a screenshot under Chromium:
> ![Capture d’écran_2019-05-20_16-38-00](https://user-images.githubusercontent.com/562352/58029829-b0ae6d00-7b1d-11e9-9aba-2162d89885ce.png)
> 
> If I use 90% zoom, the "yes" button appear.

Do you possibly use some high DPI setting/text scaling in the OS? I'm currently unable to reproduce the error in current Firefox ESR or Chrome stable - independently of the window size.
![Unbenannt](https://user-images.githubusercontent.com/87124/58054527-1bca6480-7b5b-11e9-8a59-441106b5c3c5.PNG)![Unbenannt_2](https://user-images.githubusercontent.com/87124/58054528-1bca6480-7b5b-11e9-8c5d-5751139e307f.PNG)

> This is the same as #1287, I guess. I use Safari on iMac and iPad. OFF is unusable on an iPad.

I don't have an iDevice to compare. All I can say is that it looks fine on Chrome stable on Android. 😞 
![Screenshot_20190520-235111_Chrome](https://user-images.githubusercontent.com/87124/58054753-df4b3880-7b5b-11e9-9989-5e52d6e56eba.png)![Screenshot_20190520-235055_Chrome](https://user-images.githubusercontent.com/87124/58054756-e114fc00-7b5b-11e9-8013-cceaedbaa3c0.png)

**Comment by aleene** [comment] 2019-05-21 06:42
![IMG_0596](https://user-images.githubusercontent.com/1329905/58073750-bcdd0d80-7ba3-11e9-8ac8-57e0eff1dbee.png)
So it is ok on firefox on iPad. I noticed that the selection box is left aligned. On Safari I probably do not see it as it is right aligned. I guess the issue is related to the adaptation and window size detection?

**Comment by CharlesNepote** [comment] 2019-05-21 09:22
I check all my parameters and I must admit my Firefox is set up with a 133% zoom by default. It works well with 120, 110 or 100% zoom.

That said, I still have the issue in many configurations:
- @ 1920x1080: Chromium 100, 110, 125%: KO (button not visible)
- @ 1920x1080: Chromium 75, 80, 90, 150%: OK
- @ 1920x1080: Firefox 133, 150, 170%: KO
- @ 1920x1080: Firefox under-100, 100, 110, 120, 200, 240%: OK

More and more people use a default zoom as I do (for example, because some laptops have a high resolution with a little screen).

**Comment by stephanegigandet** [comment] 2019-05-29 21:00
Same issue on my daughter's laptop. Why don't we just align both the text and the buttons to the left? (with the buttons under the text, as in this image : https://user-images.githubusercontent.com/87124/58054527-1bca6480-7b5b-11e9-8a59-441106b5c3c5.PNG )

While we are at it, the "Save" button cannot be seen entirely either, it's too much to the right depending on window size. Same thing: let's just align it to the left.

**Comment by stephanegigandet** [comment] 2019-06-02 16:24
@aleene @CharlesNepote : for the Save button, I made a fix that is currently on the dev server:
https://fr.openfoodfacts.org/cgi/product.pl?type=edit&code=3484700000978

Can you try?

If it works, the same solution can probably be applied for Robotoff.

**Comment by aleene** [comment] 2019-06-02 16:39
Negative.

Everything scales well, excepte the comments field for the save.

**Comment by stephanegigandet** [comment] 2019-06-02 16:55
I sent the wrong link, here is the dev server: https://fr.dev.openfoodfacts.org/cgi/product.pl?type=edit&code=5411188120957

**Comment by aleene** [comment] 2019-06-02 17:18
Looks good

**Comment by VaiTon** [comment] 2019-06-05 09:22
Fixed with c8deab4 @stephanegigandet

**Comment by stephanegigandet** [comment] 2019-06-06 17:56
Deployed.

**Closed by stephanegigandet** 2019-06-06 17:56 UTC
Labels: P1 candidate, bug, css, frontend, html
