### ISSUE TITLE
Donation baner is empty

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#5786] opened 2021-09-29 15:22 UTC
### Describe the bug

At least for us, uk, es.openfoodfacts.org.

![image](https://user-images.githubusercontent.com/562352/135299104-859ff70d-5480-4dcc-af58-da1c59945926.png)

### To Reproduce

Go to https://es.openfoodfacts.org/

### Expected behavior

...

### Type of device

Browser

**Comment by teolemon** [comment] 2021-09-29 15:23
Duplicate of #5776 
Fixed by #5784

**Closed by teolemon** 2021-09-29 15:23 UTC
Labels: bug
