### ISSUE TITLE
Missing letter in product log (french)

### ISSUE THREAD

**Issue by jb1415** [openfoodfacts/openfoodfacts-server#195] opened 2016-01-22 13:10 UTC
"Cration" =/= "Création"
![sans titre](https://cloud.githubusercontent.com/assets/14819001/12511470/d20bea28-c111-11e5-8840-dbc2c4f2a5f4.png)

**Comment by hangy** [comment] 2017-01-15 11:00
Has to have been caused by a typo in the code that's not here before. I believe this will be fixed well enough with #600.

**Closed by hangy** 2017-01-15 11:00 UTC
Labels: 5 minute fix, bug
