### ISSUE TITLE
support for gettext

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#55] opened 2015-03-04 08:36 UTC
In order to provide a framework to do translation, productopener  should use gettext

**Comment by teolemon** [comment] 2015-05-03 08:08
http://search.cpan.org/~pvandry/gettext-1.05/gettext.pm

**Comment by hangy** [comment] 2015-12-05 11:25
Is this a duplicate of #3?

**Comment by teolemon** [comment] 2016-05-15 15:33
use POSIX qw (setlocale);
use Locale::gettext;
use Locale::TextDomain ('script');

#And the messages to be translated/localized
print __"String to be translated/localized."; #or
print gettext("Another string to be translated/localized");

**Comment by teolemon** [comment] 2017-01-22 20:04
solved by @stephanegigandet

**Closed by teolemon** 2017-01-22 20:04 UTC
Labels: translations
