### ISSUE TITLE
json _100g encoding

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#772] opened 2017-03-03 13:47 UTC
I finally figured out my problem with the nutrition numbers.

If the number contains a "."(?), it is encoded as a number: `"potassium_100g":0.011`
if the number does not contain a ".", it is encoded a string: `"ph_100g":"6"`

This should be made consistent.

**Comment by stephanegigandet** [comment] 2019-05-06 11:07
This is caused by Perl that does not have types, and as a result the values can be stored as strings or numbers. I tried many times to force the type to numbers (e.g. by adding 0.0 to the value) but it's clearly not working, or not working everywhere...

**Comment by CharlesNepote** [comment] 2019-05-06 11:18
@stephanegigandet Can this helps? => https://metacpan.org/pod/JSON#PERL-%3E-JSON

See the following part:
> You can force the type to be a number by numifying it [...]

**Comment by stephanegigandet** [comment] 2019-05-06 11:48
Right, that's what we have been trying to do in the past, but it hasn't been enough. I will try to move the numification right before we store the product, hopefully it will help.

**Comment by stephanegigandet** [comment] 2019-05-10 10:07
I made a mistake and the _label values (that are strings) were converted to number (0)... I'm going to add them back. This is for nutrients that are not recognized: https://world.openfoodfacts.org/unknown-nutrients

**Comment by stephanegigandet** [comment] 2019-05-10 11:34
1810 products with unknown nutrients were affected.

Query to find them:

use boolean;
$query_ref->{unknown_nutrients_tags} = { '$exists' => true,  '$ne' => [] };

**Comment by stephanegigandet** [comment] 2019-05-10 12:19
Fixed in production, closing.

**Closed by stephanegigandet** 2019-05-10 12:19 UTC
Labels: api, nutrition facts
