### ISSUE TITLE
Refreshing the USDA import

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#946] opened 2017-11-12 19:54 UTC
- 294k foods found as opposed to 175k (dec 2019)
- No more truncated ingredients lists.
- Latest version (december 2019) https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_branded_food_csv_2019-12-17.zip

We're interested in the Branded Dataset: https://fdc.nal.usda.gov/download-datasets.html
Sample product: https://fdc.nal.usda.gov/fdc-app.html#/food-details/424267/nutrients

**Comment by teolemon** [comment] 2017-11-12 20:22
https://us.openfoodfacts.org/product/0076958552557/pretzels-milk-chocolate-covered-free-range-snack-co

**Comment by teolemon** [comment] 2017-11-12 20:22
https://ndb.nal.usda.gov/ndb/foods/show/177192

**Comment by teolemon** [comment] 2020-01-10 15:19
We're interested in the Branded Dataset: https://fdc.nal.usda.gov/download-datasets.html

**Comment by teolemon** [comment] 2020-01-10 15:20
https://fdc.nal.usda.gov/fdc-app.html#/food-details/344136/nutrients

**Comment by teolemon** [comment] 2020-01-13 08:07
```
mbp-de-pierre:FoodData_Central_branded_food_csv_2019-12-17 pierre$ head -5 *
==> Download_&_API_Field_Descriptions_Dec2019.pdf <==
%????1.6
              1/L 188566/O 119/E 66251/N 12/T 188067/H [ 483 350]>>
<</DecodeParms<</Columns 5/Predictor 12>>/Filter/FlateDecode/ID[<ADD12F9BCC82DB47B63DA561EBF3E79B><803D807A10B40444AFB1FCAAF7DB1CA7>]/Index[117 21]/Info 116 0 R/Length 74/Prev 188068/Root 118 0 R/Size 138/Type/XRef/W[1 3 1]>>stream
h?bbd```b``6?
              ??D?Ȃş?ŧ?Ȃ?`?y ?9
H22?????10?a?

==> all_downloaded_table_record_counts.csv <==
"Table","Number of Records"
"branded_food","331262"
"food","331262"
"food_attribute","78734"
"food_nutrient","4516179"

==> branded_food.csv <==
"fdc_id","brand_owner","gtin_upc","ingredients","serving_size","serving_size_unit","household_serving_fulltext","branded_food_category","data_source","modified_date","available_date"
"356425","G. T. Japan, Inc.","019022128593","ICE CREAM INGREDIENTS: MILK, CREAM, SUGAR, STRAWBERRIES (STRAWBERRIES, SUGAR), CORN SYRUP SOLIDS, SKIM MILK, WHEY, NATURAL FLAVOR, GUAR GUM, MONO & DIGLYCERIDES, BEET JUICE AND BEET POWDER (FOR COLOR), CELLULOSE GUM, LOCUST BEAN GUM, CARRAGEENAN. COATING INGREDIENTS: SUGAR, WATER, RICE FLOUR, TREHALOSE, EGG WHITES, BEET JUICE AND BEET POWDER (FOR COLOR), DUSTED WITH CORN & POTATO STARCH","40","g","1 PIECE","Ice Cream & Frozen Yogurt","LI","2017-11-15","2017-11-15"
"356426","FRESH & EASY","5051379043735","WATER, SUGAR, TOMATO PASTE, MOLASSES, DISTILLED VINEGAR, CONTAINS 2% OR LESS OF: CORN STARCH, SALT, DRIED CHIPOTLE PEPPER, NATURAL SMOKE FLAVOR, MUSTARD FLOUR, DRIED GARLIC, DRIED ONION, SPICES.","37","g","2 Tbsp","Ketchup, Mustard, BBQ & Cheese Sauce","LI","2018-04-26","2018-04-26"
"356427","FRESH & EASY","5051379009434","SUGAR, WATER, DISTILLED VINEGAR, TOMATO PASTE, MOLASSES, MODIFIED CORN STARCH, SALT, PINEAPPLE JUICE CONCENTRATE, CONTAINS 1% OR LESS OF: JALAPENO PEPPERS, SPICE, CARAMEL COLOR, NATURAL FLAVOR, XANTHAN GUM, GARLIC POWDER, TAMARIND EXTRACT.","34","g","2 Tbsp","Ketchup, Mustard, BBQ & Cheese Sauce","LI","2018-04-26","2018-04-26"
"356428","FRESH & EASY","5051379019969","TOMATO PUREE (WATER, TOMATO PASTE), SUGAR, DISTILLED VINEGAR, MOLASSES, WATER, MODIFIED CORN STARCH, SALT, BOURBON WHISKEY, CONTAINS 1% OR LESS OF: MUSTARD FLOUR, SPICE, DRIED ONION, DRIED GARLIC, NATURAL FLAVOR, XANTHAN GUM, CARAMEL COLOR.","35","g","2 Tbsp","Ketchup, Mustard, BBQ & Cheese Sauce","LI","2018-04-26","2018-04-26"

==> food.csv <==
"fdc_id","data_type","description","food_category_id","publication_date"
"356425","branded_food","MOCHI ICE CREAM BONBONS","","2019-04-01"
"356426","branded_food","CHIPOTLE BARBECUE SAUCE","","2019-04-01"
"356427","branded_food","HOT & SPICY BARBECUE SAUCE","","2019-04-01"
"356428","branded_food","BARBECUE SAUCE","","2019-04-01"

==> food_attribute.csv <==
"id","fdc_id","seq_num","food_attribute_type_id","name","value"
"28748","615758","","998","Nutrient Removed","6"
"28750","615758","","998","Description","2"
"28752","615758","","998","Nutrient Added","5"
"28754","615758","","998","Serving Size","7"

==> food_nutrient.csv <==
"id","fdc_id","nutrient_id","amount","data_points","derivation_id","min","max","median","footnote","min_year_acquired"
"3383047","356425","1079","0","","75","","","","",""
"3383048","356425","1087","50","","75","","","","",""
"3383049","356425","1089","0","","75","","","","",""
"3383050","356425","1104","0","","75","","","","",""

==> food_update_log_entry.csv <==
"id","description","last_updated"
"356425","MOCHI ICE CREAM BONBONS","2019-04-01"
"356426","CHIPOTLE BARBECUE SAUCE","2019-04-01"
"356427","HOT & SPICY BARBECUE SAUCE","2019-04-01"
"356428","BARBECUE SAUCE","2019-04-01"
```

**Comment by bredowmax** [comment] 2020-03-09 11:22
USDA has deprecated the old database and is now using FoodDataCentral. Has this been updated since 2017?

https://openfoodfacts.slack.com/archives/C03BNT0K8/p1581360964020700

**Comment by bredowmax** [comment] 2020-03-14 14:49
Btw, this seems to be a duplicate of #650?

**Comment by VaiTon** [comment] 2020-04-03 14:51
Can we close in favour of #650?

**Closed** 2020-09-30 17:56 UTC
Labels: data import, data quality, help wanted, us project
