### ISSUE TITLE
Maps are broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1710] opened 2019-03-14 16:49 UTC
```
{ product_name:'Dos de la mer', brands:'Vici', url: 'https://world.openfoodfacts.org/product/4770190084161', img:'<img src="https://static.openfoodfacts.org/images/products/477/019/008/4161/front_fr.16.100.jpg" width="70" height="100" srcset="https://static.openfoodfacts.org/images/products/477/019/008/4161/front_fr.16.200.jpg 2x" alt="Dos de la mer - Product" /> ', origins:'Manufacturing or processing places: Lituanie<br>', geo:[Birutės g. 50 . Plungės raj. . Lithuania,55.9172451]},
```
``` 
, geo:[Birutės g. 50 . Plungės raj. . Lithuania,55.9172451]
```
Here's a normal line:
``` 
origins:'Origins of ingredients: France<br>', geo:[47.25,0.583333]
```

**Comment by teolemon** [comment] 2019-03-14 16:50
https://world.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=states&tag_contains_0=contains&tag_0=packaging%20code%20completed&sort_by=unique_scans_n&page_size=20&axis_x=energy&axis_y=products_n&generate_map=1

**Comment by hangy** [comment] 2019-03-14 18:04
Duplicate of #1671

**Closed by hangy** 2019-03-14 18:04 UTC
Labels: maps
