### ISSUE TITLE
It's impossible to crop an image from mobile web

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1672] opened 2019-02-18 22:32 UTC
The loader goes into an infinite loop

![image](https://user-images.githubusercontent.com/1689815/52979324-52b2a200-33d5-11e9-9c5c-68b6e9a69504.png)

**Comment by hangy** [comment] 2019-02-28 18:25
Duplicate of #311

**Closed by hangy** 2019-02-28 18:25 UTC
Labels: bug, edition
