### ISSUE TITLE
Unmatched ) in regex; marked by <-- HERE in m/([^,-\.;\(\)/]*)\b(contains)\b(:|\(|\[| | of )+((_?(CIT

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#4621] opened 2020-12-11 14:17 UTC
When trying to move a product from Open Beauty Facts to Open Food Facts
Software error:
Unmatched ) in regex; marked by <-- HERE in m/([^,-\.;\(\)/]*)\b(contains)\b(:|\(|\[| | of )+((_?(CITRUS SINENSIS (syn.: AURANTIUM DULCIS) PEEL OIL EXPRESSED|CITRUS SINENSIS (syn.: AURANTIUM DULCIS) PEEL OIL EXPRESSEDs|CINNAMOMUM CASSIA LEAF OIL CINNAMOMUM ZEYLANICUM BARK OIL|CINNAMOMUM CASSIA LEAF OIL CINNAMOMUM ZEYLANICUM BARK OILs|7Î±-HEXAHYDRO-4â€š7-METHANO-1H-INDEN-5(OR 6)-YL ACETATE|7Î±-HEXAHYDRO-4â€š7-METHANO-1H-INDEN-5(OR 6)-YL ACETATEs|HYDROXYISOHEXYL 3-CYCLOHEXENE CARBOXALDEHYDE (HICC)*|HYDROXYISOHEXYL 3-CYCLOHEXENE CARBOXALDEHYDE (HICC)*s|6-ETHYLIDENEOCTAHYDRO-5â€š8-METHANO-2H-BENZO-1-PYRAN|6-ETHYLIDENEOCTAHYDRO-5â€š8-METHANO-2H-BENZO-1-PYRANs|Jasminum Sambac Flower CERA / Extract / Water|Jasminum Sambac Flower CERA / Extract / Waters|3-TRIMETHYL-3-CYCLOPENTEN-1-YL)-2-BUTEN-1-OL|3-TRIMETHYL-3-CYCLOPENTEN-1-YL)-2-BUTEN-1-OLs|2â€š4-dimethyl-3-cyclohexen-1-carboxaldehyde Â§|2â€š4-dimethyl-3-cyclohexen-1-carboxaldehyde Â§s|alpha-CYCLOHEXYLIDENE BENZENEACETONITRILE|alpha-CYCLOHEXYLIDENE BENZENEACETONITRILEs|CYMBOPOGON NARDUS / WINTERIANUS HERB OIL|CYMBOPOGON NARDUS / WINTERIANUS HERB OILs|CITRUS AURANTIUM AMARA FLOWER / PEEL OIL|CITRUS AURANTIUM AMARA FLOWER / PEEL OILs|TETRAMETHYL ACETYLOCTAHYDRONAPHTHALENES|TETRAMETHYL ACETYLOCTAHYDRONAPHTHALENESs|CYMBOPOGON CITRATUS / SCHOENANTHUS OILS|CYMBOPOGON CITRATUS / SCHOENANTHUS OILSs|p-Isobutyl-Î±-methyl hydrocinnamaldehdye|p-Isobutyl-Î±-methyl hydrocinnamaldehdyes|DIMETHYLBENZYL CARBINYL ACETATE (DMBCA)|DIMETHYLBENZYL CARBINYL ACETATE (DMBCA)s|EUGENIA CARYOPHYLLUS LEAF / FLOWER OIL|EUGENIA CARYOPHYLLUS LEAF / FLOWER OILs|Perillaldehyde p-Mentha-1â€š8-dien-7-al|Perillaldehyde p-Mentha-1â€š8-dien-7-als|TRIMETHYL-BENZENEPROPANOL (Majantol)|TRIMETHYL-BENZENEPROPANOL (Majantol)s|p-tert. -Butyldihydrocinnamaldehyde|p-tert. -Butyldihydrocinnamaldehydes|CANANGA ODORATAÂ and Ylang-ylang oil|CANANGA ODORATAÂ and Ylang-ylang oils|METHYLENEDIOXYPHENYL METHYLPROPANAL|METHYLENEDIOXYPHENYL METHYLPROPANALs|HEXAHYDRO-METHANOINDENYL PROPIONATE|HEXAHYDRO-METHANOINDENYL PROPIONATEs|JASMINUM GRANDIFLORUM / OFFICINALE|JASMINUM GRANDIFLORUM / OFFICINALEs|CITRUS BERGAMIA PEEL OIL EXPRESSED|CITRUS BERGAMIA PEEL OIL EXPRESSEDs|METHYL IONONE (mixture of isomers)|METHYL IONONE (mixture of isomers)s|TERPINEOL ACETATE (Isomer mixture)|TERPINEOL ACETATE (Isomer mixture)s|CITRUS LIMONUM PEEL OIL EXPRESSED|CITRUS LIMONUM PEEL OIL EXPRESSEDs|4-Methoxy-Î±-methyl benzenpropanal|4-Methoxy-Î±-methyl benzenpropanals|alpha-SANTALOL and beta-SANTALOL|alpha-SANTALOL and beta-SANTALOLs|Nerolidol (isomer not specified)|Nerolidol (isomer not specified)s|DIMETHYLTETRAHYDRO BENZALDEHYDE|DIMETHYLTETRAHYDRO BENZALDEHYDEs|CITRUS AURANTIUM AMARA LEAF OIL|CITRUS AURANTIUM AMARA LEAF OILs|3â€š7-DIMETHYL-1â€š6-NONADIEN-3-OL|3â€š7-DIMETHYL-1â€š6-NONADIEN-3-OLs|TERPINEOL (mixture of isomers)|TERPINEOL (mixture of isomers)s|BUTYLPHENYL METHYLPROPIONAL *|BUTYLPHENYL METHYLPROPIONAL *s|alpha-PINENE and beta-PINENE|alpha-PINENE and beta-PINENEs|(DAMASCENONE ) ROSE KETONE-4|(DAMASCENONE ) ROSE KETONE-4s|CYCLOPENTENYL)PENT-4-EN-2-OL|CYCLOPENTENYL) <-- HERE PENT-4-EN-2-OLs|EVERNIA FURFURACEA EXTRACT*|EVERNIA FURFURACEA EXTRACT*s|ROSE FLOWER OIL (ROSA SPP.)|ROSE FLOWER OIL (ROSA SPP.)s|2-Hexylidene cyclopentanone|2-Hexylidene cyclopentanones|trans-trans-delta-DAMASCONE|trans-trans-delta-DAMASCONEs|TRICYCLODECENYL PROPIONATE|TRICYCLODECENYL PROPIONATEs|Î±-Methyl cinnamic aldehyde|Î±-Methyl cinnamic aldehydes|EVERNIA PRUNASTRI EXTRACT*|EVERNIA PRUNASTRI EXTRACT*s|CEDRUS ATLANTICA BARK OIL|CEDRUS ATLANTICA BARK OILs|METHOXYTRIMETHYLHEPTANO L|METHOXYTRIMETHYLHEPTANO Ls|2-Methoxy-4-methylphenol|2-Methoxy-4-methylphenols|EUCALYPTUS SPP. LEAF OIL|EUCALYPTUS SPP. LEAF OILs|ILLICIUM VERUM FRUIT OIL|ILLICIUM VERUM FRUIT OILs|beta-CARYOPHYLLENE (ox.)|beta-CARYOPHYLLENE (ox.)s|CEDRUS DEODARA WOOD OIL|CEDRUS DEODARA WOOD OILs|6-TRIMETHYLBENZALDEHYDE|6-TRIMETHYLBENZALDEHYDEs|ACORUS CALAMUS ROOT OIL|ACORUS CALAMUS ROOT OILs|IONONE isomeric mixture|IONONE isomeric mixtures|ETHYLENE DODECANEDIOATE|ETHYLENE DODECANEDIOATEs|METHYL OCTINE CARBONATE|METHYL OCTINE CARBONATEs|alpha-DAMASCONE (TMCHB)|alpha-DAMASCONE (TMCHB)s|alpha-ISOMETHYL IONONE*|alpha-ISOMETHYL IONONE*s|METHYL DIHYDROJASMONATE|METHYL DIHYDROJASMONATEs|alpha-TERPINYL ACETATE|alpha-TERPINYL ACETATEs|AMYL CINNAMYL ALCOHOL*|AMYL CINNAMYL ALCOHOL*s|PELARGONIUM GRAVEOLENS|PELARGONIUM GRAVEOLENSs|HEXAMETHYLINDANOPYRAN|HEXAMETHYLINDANOPYRANs|LAVANDULA OFFICINALIS|LAVANDULA OFFICINALISs|5-METHYL-alpha-IONONE|5-METHYL-alpha-IONONEs|PROPYLIDENE PHTHALIDE|PROPYLIDENE PHTHALIDEs|VETIVERIA ZIZANOIDES|VETIVERIA ZIZANOIDESs|ISOLONGIFOLENEKETONE|ISOLONGIFOLENEKETONEs|Allyl phenoxyacetate|Allyl phenoxyacetates|trans-beta-Damascone|trans-beta-Damascones|OXACYCLOHEXADECENONE|OXACYCLOHEXADECENONEs|Phenethyl salicylate|Phenethyl salicylates|JUNIPERUS VIRGINIANA|JUNIPERUS VIRGINIANAs|trans-ROSE KETONE-5|trans-ROSE KETONE-5s|CITRONELLYL NITRILE|CITRONELLYL NITRILEs|HYDROXYCITRONELLAL*|HYDROXYCITRONELLAL*s|METHYL 2-OCTYNOATE*|METHYL 2-OCTYNOATE*s|HYDROXYCITRONELLOL|HYDROXYCITRONELLOLs|ISOAMYL SALICYLATE|ISOAMYL SALICYLATEs|CITRUS TANGERINA â€¦|CITRUS TANGERINA â€¦s|AMYLCYCLOPENTANONE|AMYLCYCLOPENTANONEs|MYROXYLON PEREIRAE|MYROXYLON PEREIRAEs|CYCLOHEXYL ACETATE|CYCLOHEXYL ACETATEs|METHOXYCITRONELLAL|METHOXYCITRONELLALs|CYCLOPENTADECANONE|CYCLOPENTADECANONEs|cis-beta-DAMASCONE|cis-beta-DAMASCONEs|BENZYL SALICYLATE*|BENZYL SALICYLATE*s|PELARGONIUM ROSEUM|PELARGONIUM ROSEUMs|PHENYLACETALDEHYDE|PHENYLACETALDEHYDEs|PINUS MUGO/PUMILA|PINUS MUGO/PUMILAs|HEXADECANOLACTONE|HEXADECANOLACTONEs|POGOSTEMON CABLIN|POGOSTEMON CABLINs|CYCLAMEN ALDEHYDE|CYCLAMEN ALDEHYDEs|CINNAMYL ALCOHOL*|CINNAMYL ALCOHOL*s|Mentha arvensis Â§|Mentha arvensis Â§s|METHYL SALICYLATE|METHYL SALICYLATEs|6-METHYL COUMARIN|6-METHYL COUMARINs|Citrus paradisi Â§|Citrus paradisi Â§s|BENZYL CINNAMATE*|BENZYL CINNAMATE*s|LAVANDULA HYBRIDA|LAVANDULA HYBRIDAs|PHENETHYL ALCOHOL|PHENETHYL ALCOHOLs|METHYL CINNAMATE|METHYL CINNAMATEs|Natural extract|Natural extracts|METHYLIONANTHEME|METHYLIONANTHEMEs|BENZYL BENZOATE*|BENZYL BENZOATE*s|METHYL p-ANISATE|METHYL p-ANISATEs|TURPENTINE (oil)|TURPENTINE (oil)s|HEXYL SALICYLATE|HEXYL SALICYLATEs|VERBENA ABSOLUTE|VERBENA ABSOLUTEs|trans-2-Hexenal|trans-2-Hexenals|LINALYL ACETATE|LINALYL ACETATEs|MENTHA PIPERITA|MENTHA PIPERITAs|GERANYL ACETATE|GERANYL ACETATEs|HEXYL CINNAMAL*|HEXYL CINNAMAL*s|alpha-TERPINEOL|alpha-TERPINEOLs|gamma-Damascone|gamma-Damascones|LAVANDULA SPICA|LAVANDULA SPICAs|2â€š3-DIHYDRO-2â€š2|2â€š3-DIHYDRO-2â€š2s|SALICYLALDEHYDE|SALICYLALDEHYDEs|AMYL SALICYLATE|AMYL SALICYLATEs|METHYLUNDECANAL|METHYLUNDECANALs|BENZYL ALCOHOL*|BENZYL ALCOHOL*s|DIHYDROMYRCENOL|DIHYDROMYRCENOLs|3-METHYL-5-(2â€š2|3-METHYL-5-(2â€š2s|delta-DAMASCONE|delta-DAMASCONEs|trans-ANETHOLE|trans-ANETHOLEs|SANTALUM ALBUM|SANTALUM ALBUMs|LAURUS NOBILIS|LAURUS NOBILISs|METHYL DECENOL|METHYL DECENOLs|TAGETES PATULA|TAGETES PATULAs|Isocyclocitral|Isocyclocitrals|BENZYL ACETATE|BENZYL ACETATEs|MENTHA SPICATA|MENTHA SPICATAs|(DL)-LIMONENE*|(DL)-LIMONENE*s|ANISE ALCOHOL*|ANISE ALCOHOL*s|2-ETHYL-4-(2â€š2|2-ETHYL-4-(2â€š2s|Dibenzyl ether|Dibenzyl ethers|ETHYL VANILLIN|ETHYL VANILLINs|AMYL CINNAMAL*|AMYL CINNAMAL*s|NARCISSUS SPP.|NARCISSUS SPP.s|PHENYLPROPANOL|PHENYLPROPANOLs|VERDYL ACETATE|VERDYL ACETATEs|3-TRIMETHYL-3-|3-TRIMETHYL-3-s|NOPYL ACETATE|NOPYL ACETATEs|LITSEA CUBEBA|LITSEA CUBEBAs|CUMINALDEHYDE|CUMINALDEHYDEs|ACETYLCEDRENE|ACETYLCEDRENEs|Longifolene Â§|Longifolene Â§s|HELIOTROPINE|HELIOTROPINEs|AMBRETTOLIDE|AMBRETTOLIDEs|alpha-IONONE|alpha-IONONEs|ISOBERGAMATE|ISOBERGAMATEs|BENZALDEHYDE|BENZALDEHYDEs|CITRONELLOL*|CITRONELLOL*s|Terpinolene|Terpinolenes|THYMUS spp.|THYMUS spp.s|Citronellal|Citronellals|SALVIA spp.|SALVIA spp.s|beta-IONONE|beta-IONONEs|ISOEUGENOL*|ISOEUGENOL*s|LINALOOL*|LINALOOL*s|COUMARIN*|COUMARIN*s|CARVACROL|CARVACROLs|GERANIOL*|GERANIOL*s|CINNAMAL*|CINNAMAL*s|FARNESOL*|FARNESOL*s|SCLAREOL|SCLAREOLs|MYRTENOL|MYRTENOLs|RHODINOL|RHODINOLs|EUGENOL*|EUGENOL*s|VANILLIN|VANILLINs|CAMPHOR|CAMPHORs|MENTHOL|MENTHOLs|CITRAL*|CITRAL*s|DECANAL|DECANALs|CARVONE|CARVONEs|MYRCENE|MYRCENEs|PHYTOL|PHYTOLs|NEROL|NEROLs|4â€š5|4â€š5s|6â€š7|6â€š7s|3Î±|3Î±s)_?( |/| / | - |,|, | and | of | and of )+)*_?(CITRUS SINENSIS (syn.: AURANTIUM DULCIS) PEEL OIL EXPRESSED|CITRUS SINENSIS (syn.: AURANTIUM DULCIS) PEEL OIL EXPRESSEDs|CINNAMOMUM CASSIA LEAF OIL CINNAMOMUM ZEYLANICUM BARK OIL|CINNAMOMUM CASSIA LEAF OIL CINNAMOMUM ZEYLANICUM BARK OILs|7Î±-HEXAHYDRO-4â€š7-METHANO-1H-INDEN-5(OR 6)-YL ACETATE|7Î±-HEXAHYDRO-4â€š7-METHANO-1H-INDEN-5(OR 6)-YL ACETATEs|HYDROXYISOHEXYL 3-CYCLOHEXENE CARBOXALDEHYDE (HICC)*|HYDROXYISOHEXYL 3-CYCLOHEXENE CARBOXALDEHYDE (HICC)*s|6-ETHYLIDENEOCTAHYDRO-5â€š8-METHANO-2H-BENZO-1-PYRAN|6-ETHYLIDENEOCTAHYDRO-5â€š8-METHANO-2H-BENZO-1-PYRANs|Jasminum Sambac Flower CERA / Extract / Water|Jasminum Sambac Flower CERA / Extract / Waters|3-TRIMETHYL-3-CYCLOPENTEN-1-YL)-2-BUTEN-1-OL|3-TRIMETHYL-3-CYCLOPENTEN-1-YL)-2-BUTEN-1-OLs|2â€š4-dimethyl-3-cyclohexen-1-carboxaldehyde Â§|2â€š4-dimethyl-3-cyclohexen-1-carboxaldehyde Â§s|alpha-CYCLOHEXYLIDENE BENZENEACETONITRILE|alpha-CYCLOHEXYLIDENE BENZENEACETONITRILEs|CYMBOPOGON NARDUS / WINTERIANUS HERB OIL|CYMBOPOGON NARDUS / WINTERIANUS HERB OILs|CITRUS AURANTIUM AMARA FLOWER / PEEL OIL|CITRUS AURANTIUM AMARA FLOWER / PEEL OILs|TETRAMETHYL ACETYLOCTAHYDRONAPHTHALENES|TETRAMETHYL ACETYLOCTAHYDRONAPHTHALENESs|CYMBOPOGON CITRATUS / SCHOENANTHUS OILS|CYMBOPOGON CITRATUS / SCHOENANTHUS OILSs|p-Isobutyl-Î±-methyl hydrocinnamaldehdye|p-Isobutyl-Î±-methyl hydrocinnamaldehdyes|DIMETHYLBENZYL CARBINYL ACETATE (DMBCA)|DIMETHYLBENZYL CARBINYL ACETATE (DMBCA)s|EUGENIA CARYOPHYLLUS LEAF / FLOWER OIL|EUGENIA CARYOPHYLLUS LEAF / FLOWER OILs|Perillaldehyde p-Mentha-1â€š8-dien-7-al|Perillaldehyde p-Mentha-1â€š8-dien-7-als|TRIMETHYL-BENZENEPROPANOL (Majantol)|TRIMETHYL-BENZENEPROPANOL (Majantol)s|p-tert. -Butyldihydrocinnamaldehyde|p-tert. -Butyldihydrocinnamaldehydes|CANANGA ODORATAÂ and Ylang-ylang oil|CANANGA ODORATAÂ and Ylang-ylang oils|METHYLENEDIOXYPHENYL METHYLPROPANAL|METHYLENEDIOXYPHENYL METHYLPROPANALs|HEXAHYDRO-METHANOINDENYL PROPIONATE|HEXAHYDRO-METHANOINDENYL PROPIONATEs|JASMINUM GRANDIFLORUM / OFFICINALE|JASMINUM GRANDIFLORUM / OFFICINALEs|CITRUS BERGAMIA PEEL OIL EXPRESSED|CITRUS BERGAMIA PEEL OIL EXPRESSEDs|METHYL IONONE (mixture of isomers)|METHYL IONONE (mixture of isomers)s|TERPINEOL ACETATE (Isomer mixture)|TERPINEOL ACETATE (Isomer mixture)s|CITRUS LIMONUM PEEL OIL EXPRESSED|CITRUS LIMONUM PEEL OIL EXPRESSEDs|4-Methoxy-Î±-methyl benzenpropanal|4-Methoxy-Î±-methyl benzenpropanals|alpha-SANTALOL and beta-SANTALOL|alpha-SANTALOL and beta-SANTALOLs|Nerolidol (isomer not specified)|Nerolidol (isomer not specified)s|DIMETHYLTETRAHYDRO BENZALDEHYDE|DIMETHYLTETRAHYDRO BENZALDEHYDEs|CITRUS AURANTIUM AMARA LEAF OIL|CITRUS AURANTIUM AMARA LEAF OILs|3â€š7-DIMETHYL-1â€š6-NONADIEN-3-OL|3â€š7-DIMETHYL-1â€š6-NONADIEN-3-OLs|TERPINEOL (mixture of isomers)|TERPINEOL (mixture of isomers)s|BUTYLPHENYL METHYLPROPIONAL *|BUTYLPHENYL METHYLPROPIONAL *s|alpha-PINENE and beta-PINENE|alpha-PINENE and beta-PINENEs|(DAMASCENONE ) ROSE KETONE-4|(DAMASCENONE ) ROSE KETONE-4s|CYCLOPENTENYL)PENT-4-EN-2-OL|CYCLOPENTENYL)PENT-4-EN-2-OLs|EVERNIA FURFURACEA EXTRACT*|EVERNIA FURFURACEA EXTRACT*s|ROSE FLOWER OIL (ROSA SPP.)|ROSE FLOWER OIL (ROSA SPP.)s|2-Hexylidene cyclopentanone|2-Hexylidene cyclopentanones|trans-trans-delta-DAMASCONE|trans-trans-delta-DAMASCONEs|TRICYCLODECENYL PROPIONATE|TRICYCLODECENYL PROPIONATEs|Î±-Methyl cinnamic aldehyde|Î±-Methyl cinnamic aldehydes|EVERNIA PRUNASTRI EXTRACT*|EVERNIA PRUNASTRI EXTRACT*s|CEDRUS ATLANTICA BARK OIL|CEDRUS ATLANTICA BARK OILs|METHOXYTRIMETHYLHEPTANO L|METHOXYTRIMETHYLHEPTANO Ls|2-Methoxy-4-methylphenol|2-Methoxy-4-methylphenols|EUCALYPTUS SPP. LEAF OIL|EUCALYPTUS SPP. LEAF OILs|ILLICIUM VERUM FRUIT OIL|ILLICIUM VERUM FRUIT OILs|beta-CARYOPHYLLENE (ox.)|beta-CARYOPHYLLENE (ox.)s|CEDRUS DEODARA WOOD OIL|CEDRUS DEODARA WOOD OILs|6-TRIMETHYLBENZALDEHYDE|6-TRIMETHYLBENZALDEHYDEs|ACORUS CALAMUS ROOT OIL|ACORUS CALAMUS ROOT OILs|IONONE isomeric mixture|IONONE isomeric mixtures|ETHYLENE DODECANEDIOATE|ETHYLENE DODECANEDIOATEs|METHYL OCTINE CARBONATE|METHYL OCTINE CARBONATEs|alpha-DAMASCONE (TMCHB)|alpha-DAMASCONE (TMCHB)s|alpha-ISOMETHYL IONONE*|alpha-ISOMETHYL IONONE*s|METHYL DIHYDROJASMONATE|METHYL DIHYDROJASMONATEs|alpha-TERPINYL ACETATE|alpha-TERPINYL ACETATEs|AMYL CINNAMYL ALCOHOL*|AMYL CINNAMYL ALCOHOL*s|PELARGONIUM GRAVEOLENS|PELARGONIUM GRAVEOLENSs|HEXAMETHYLINDANOPYRAN|HEXAMETHYLINDANOPYRANs|LAVANDULA OFFICINALIS|LAVANDULA OFFICINALISs|5-METHYL-alpha-IONONE|5-METHYL-alpha-IONONEs|PROPYLIDENE PHTHALIDE|PROPYLIDENE PHTHALIDEs|VETIVERIA ZIZANOIDES|VETIVERIA ZIZANOIDESs|ISOLONGIFOLENEKETONE|ISOLONGIFOLENEKETONEs|Allyl phenoxyacetate|Allyl phenoxyacetates|trans-beta-Damascone|trans-beta-Damascones|OXACYCLOHEXADECENONE|OXACYCLOHEXADECENONEs|Phenethyl salicylate|Phenethyl salicylates|JUNIPERUS VIRGINIANA|JUNIPERUS VIRGINIANAs|trans-ROSE KETONE-5|trans-ROSE KETONE-5s|CITRONELLYL NITRILE|CITRONELLYL NITRILEs|HYDROXYCITRONELLAL*|HYDROXYCITRONELLAL*s|METHYL 2-OCTYNOATE*|METHYL 2-OCTYNOATE*s|HYDROXYCITRONELLOL|HYDROXYCITRONELLOLs|ISOAMYL SALICYLATE|ISOAMYL SALICYLATEs|CITRUS TANGERINA â€¦|CITRUS TANGERINA â€¦s|AMYLCYCLOPENTANONE|AMYLCYCLOPENTANONEs|MYROXYLON PEREIRAE|MYROXYLON PEREIRAEs|CYCLOHEXYL ACETATE|CYCLOHEXYL ACETATEs|METHOXYCITRONELLAL|METHOXYCITRONELLALs|CYCLOPENTADECANONE|CYCLOPENTADECANONEs|cis-beta-DAMASCONE|cis-beta-DAMASCONEs|BENZYL SALICYLATE*|BENZYL SALICYLATE*s|PELARGONIUM ROSEUM|PELARGONIUM ROSEUMs|PHENYLACETALDEHYDE|PHENYLACETALDEHYDEs|PINUS MUGO/PUMILA|PINUS MUGO/PUMILAs|HEXADECANOLACTONE|HEXADECANOLACTONEs|POGOSTEMON CABLIN|POGOSTEMON CABLINs|CYCLAMEN ALDEHYDE|CYCLAMEN ALDEHYDEs|CINNAMYL ALCOHOL*|CINNAMYL ALCOHOL*s|Mentha arvensis Â§|Mentha arvensis Â§s|METHYL SALICYLATE|METHYL SALICYLATEs|6-METHYL COUMARIN|6-METHYL COUMARINs|Citrus paradisi Â§|Citrus paradisi Â§s|BENZYL CINNAMATE*|BENZYL CINNAMATE*s|LAVANDULA HYBRIDA|LAVANDULA HYBRIDAs|PHENETHYL ALCOHOL|PHENETHYL ALCOHOLs|METHYL CINNAMATE|METHYL CINNAMATEs|Natural extract|Natural extracts|METHYLIONANTHEME|METHYLIONANTHEMEs|BENZYL BENZOATE*|BENZYL BENZOATE*s|METHYL p-ANISATE|METHYL p-ANISATEs|TURPENTINE (oil)|TURPENTINE (oil)s|HEXYL SALICYLATE|HEXYL SALICYLATEs|VERBENA ABSOLUTE|VERBENA ABSOLUTEs|trans-2-Hexenal|trans-2-Hexenals|LINALYL ACETATE|LINALYL ACETATEs|MENTHA PIPERITA|MENTHA PIPERITAs|GERANYL ACETATE|GERANYL ACETATEs|HEXYL CINNAMAL*|HEXYL CINNAMAL*s|alpha-TERPINEOL|alpha-TERPINEOLs|gamma-Damascone|gamma-Damascones|LAVANDULA SPICA|LAVANDULA SPICAs|2â€š3-DIHYDRO-2â€š2|2â€š3-DIHYDRO-2â€š2s|SALICYLALDEHYDE|SALICYLALDEHYDEs|AMYL SALICYLATE|AMYL SALICYLATEs|METHYLUNDECANAL|METHYLUNDECANALs|BENZYL ALCOHOL*|BENZYL ALCOHOL*s|DIHYDROMYRCENOL|DIHYDROMYRCENOLs|3-METHYL-5-(2â€š2|3-METHYL-5-(2â€š2s|delta-DAMASCONE|delta-DAMASCONEs|trans-ANETHOLE|trans-ANETHOLEs|SANTALUM ALBUM|SANTALUM ALBUMs|LAURUS NOBILIS|LAURUS NOBILISs|METHYL DECENOL|METHYL DECENOLs|TAGETES PATULA|TAGETES PATULAs|Isocyclocitral|Isocyclocitrals|BENZYL ACETATE|BENZYL ACETATEs|MENTHA SPICATA|MENTHA SPICATAs|(DL)-LIMONENE*|(DL)-LIMONENE*s|ANISE ALCOHOL*|ANISE ALCOHOL*s|2-ETHYL-4-(2â€š2|2-ETHYL-4-(2â€š2s|Dibenzyl ether|Dibenzyl ethers|ETHYL VANILLIN|ETHYL VANILLINs|AMYL CINNAMAL*|AMYL CINNAMAL*s|NARCISSUS SPP.|NARCISSUS SPP.s|PHENYLPROPANOL|PHENYLPROPANOLs|VERDYL ACETATE|VERDYL ACETATEs|3-TRIMETHYL-3-|3-TRIMETHYL-3-s|NOPYL ACETATE|NOPYL ACETATEs|LITSEA CUBEBA|LITSEA CUBEBAs|CUMINALDEHYDE|CUMINALDEHYDEs|ACETYLCEDRENE|ACETYLCEDRENEs|Longifolene Â§|Longifolene Â§s|HELIOTROPINE|HELIOTROPINEs|AMBRETTOLIDE|AMBRETTOLIDEs|alpha-IONONE|alpha-IONONEs|ISOBERGAMATE|ISOBERGAMATEs|BENZALDEHYDE|BENZALDEHYDEs|CITRONELLOL*|CITRONELLOL*s|Terpinolene|Terpinolenes|THYMUS spp.|THYMUS spp.s|Citronellal|Citronellals|SALVIA spp.|SALVIA spp.s|beta-IONONE|beta-IONONEs|ISOEUGENOL*|ISOEUGENOL*s|LINALOOL*|LINALOOL*s|COUMARIN*|COUMARIN*s|CARVACROL|CARVACROLs|GERANIOL*|GERANIOL*s|CINNAMAL*|CINNAMAL*s|FARNESOL*|FARNESOL*s|SCLAREOL|SCLAREOLs|MYRTENOL|MYRTENOLs|RHODINOL|RHODINOLs|EUGENOL*|EUGENOL*s|VANILLIN|VANILLINs|CAMPHOR|CAMPHORs|MENTHOL|MENTHOLs|CITRAL*|CITRAL*s|DECANAL|DECANALs|CARVONE|CARVONEs|MYRCENE|MYRCENEs|PHYTOL|PHYTOLs|NEROL|NEROLs|4â€š5|4â€š5s|6â€š7|6â€š7s|3Î±|3Î±s)_?)\b((\s)())*(\s?(\)|\]))?/ at /srv/obf/lib/ProductOpener/Ingredients.pm line 3403.
For help, please send mail to the webmaster (contact@openfoodfacts.org), giving this error message and the time and date of the error.

**Comment by teolemon** [comment] 2020-12-11 14:34
https://world.openbeautyfacts.org/cgi/product.pl?type=edit&code=0077017400000

**Comment by svensven** [comment] 2020-12-15 16:13
duplicate of #4290 ?

**Comment by VaiTon** [comment] 2020-12-31 23:39
Closing in favor of #4290

**Closed by VaiTon** 2020-12-31 23:40 UTC
Labels: bug, open beauty facts
