### ISSUE TITLE
Uncomplete products among completed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#309] opened 2016-05-21 23:47 UTC
http://world.openfoodfacts.org/3000

**Comment by TaciteOFF** [comment] 2016-05-22 05:36
It's a normal behavior. The pages contains all products, with the completed one first and the incompleted ones at the end.
3000 * 20 = 60K
We don't have 60K completed products yet

**Comment by stephanegigandet** [comment] 2016-06-11 18:15
What Tacite says is correct. If you want complete products only, use /state/complete.
The last page right now is http://world.openfoodfacts.org/state/complete/2245
On http://world.openfoodfacts.org/2245 you then get the incomplete products.
Closing the bug as it is the intended behavior.

**Closed by stephanegigandet** 2016-06-11 18:15 UTC
