### ISSUE TITLE
TEST FAIL - Salt becomes orange

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1740] opened 2019-04-20 10:22 UTC
```
#   Failed test at t/tags.t line 289.
#     Structures begin differing at:
#          $got->[3] = 'en:salt'
#     $expected->[3] = 'en:orange'
# [
#   'en:fruit',
#   'en:citrus-fruit',
#   'en:fruit-juice',
#   'en:salt',
#   'en:sugar',
#   'en:orange',
#   'en:orange-juice',
#   'en:concentrated-orange-juice'
# ]
# Looks like you failed 7 tests of 33.
t/tags.t .................. 
Dubious, test returned 7 (wstat 1792, 0x700)
Failed 7/33 subtests 
t/text.t .................. ok

```

**Comment by hangy** [comment] 2019-05-11 08:18
Duplicate of #1727

**Closed by hangy** 2019-05-11 08:18 UTC
