### ISSUE TITLE
Dutch data quality facet gives wrong results

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#9397] opened 2023-11-24 08:22 UTC
### What
Dutch data quality facet gives wrong results. Instead of showing the errors for NL-products, the errors for the world are shown.

### Steps to reproduce the behavior
See https://nl.openfoodfacts.org/data-quality-errors

### Expected behavior
Only see the dutch errors

**Comment by CharlesNepote** [comment] 2023-11-26 11:08
Same or similar issue happens on https://world.openfoodfacts.org/data-quality-errors with errors that are not errors but only warnings.

**Comment by alexgarel** [comment] 2023-12-12 14:41
@john-gom any idea ?

**Comment by john-gom** [comment] 2023-12-13 08:33
I think the queries are returning the right data - https://nl.openfoodfacts.org/data-quality-errors is returning less data than https://world.openfoodfacts.org/data-quality-errors and I can see that the country is being restricted to en:netherlands for the "nl" query.

**Comment by aleene** [comment] 2023-12-13 16:03
Still strange, so much different than what we had before. Note that none(?) of the entries contain any products.

**Comment by CharlesNepote** [comment] 2023-12-14 11:56
@john-gom: I don't know where is the issue but I can say that /data-quality-errors are completely false.

https://world.openfoodfacts.org/data-quality-errors or https://nl.openfoodfacts.org/data-quality-errors are returning not only data quality errors but also data quality warnings, which are different.

Example: `Food groups 3 unknown` (the first in the list) is NOT a data-quality-error and should not be listed here. Maybe that's why [Food groups 3 unknown](https://world.openfoodfacts.org/data-quality-error/food-groups-3-unknown) is empty?

Here are the data quality errors: https://wiki.openfoodfacts.org/List_of_data_quality_errors_(generated)

**Comment by john-gom** [comment] 2023-12-14 22:55
Hi @CharlesNepote . I'll have to investigate whether the problem is at the source or is being introduced in off-query

**Comment by john-gom** [comment] 2023-12-15 08:56
OK, I see the problem. The data_quality and data_quality_errors tags have been transposed. I'll see if I can get a PR raised as soon as possible

**Comment by aleene** [comment] 2023-12-19 12:36
Not yet the result as expected:
- counts seem wrong;
- no products shown (related to counts?);
- no way to zoom in on errors (and leave warnings aside)

**Comment by john-gom** [comment] 2023-12-20 16:00
Hi @CharlesNepote , @aleene . This should not be resolved in Staging. Can you check that the figures look right now? https://nl.openfoodfacts.net/data-quality-errors

**Comment by CharlesNepote** [comment] 2023-12-20 16:23
Yes that's fine @john-gom, thank you very much!

**Comment by john-gom** [comment] 2024-01-18 15:29
@CharlesNepote , @aleene this has now been deployed to production.

**Closed by john-gom** 2024-01-18 15:29 UTC
Labels: 🐛 bug, 🎯 P1, 🧽 Data quality

**Comment by CharlesNepote** [comment] 2024-01-18 17:10
Works great, thanks @john-gom !
