### ISSUE TITLE
Ignore things like "used to protect quality" on US ingredient lists

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#3288] opened 2020-04-18 13:08 UTC
Ignore things like "used to protect quality" on US ingredient lists
https://us.openfoodfacts.org/product/0048001265844/real-mayonnaise-best-foods
This prevent several analysis from being conclusive

**Comment by teolemon** [comment] 2020-04-18 13:17
![image](https://user-images.githubusercontent.com/1689815/79638794-b24a4000-8187-11ea-9018-9225e214755d.png)

**Comment by teolemon** [comment] 2020-04-18 13:18
![image](https://user-images.githubusercontent.com/1689815/79638810-caba5a80-8187-11ea-8a49-1f4a97e2b7e6.png)

**Comment by stephanegigandet** [comment] 2020-04-18 14:26
It's part of a broader pattern for indicating the additives functions.

**Comment by stephanegigandet** [comment] 2020-04-24 19:06
Duplicate of #3089

**Closed by stephanegigandet** 2020-04-24 19:06 UTC
Labels: feature, ingredients-analysis
