### ISSUE TITLE
Confusing error message for certain inputs!

### ISSUE THREAD

**Issue by Anubhav-Bhargava** [openfoodfacts/openfoodfacts-server#1156] opened 2018-03-25 07:25 UTC
**Summary:** 

When we give a random string in both the user name and the password form it redirects to the Error message on a new web page. But when done the same using *randomstring@randomstring* in the user name field, it redirects to the webpage which says "Sign in See You Soon!"

**Steps to reproduce:** 

username:- randomstring@randomstring
password:-randomstring

**Expected behavior:** 

If any one of the user name or password is not correct then it should redirect to the screen displaying the error message.

**Observed behavior:** 

It is currently redirecting to the page saying "Sign in See You soon".

**Comment by hangy** [comment] 2018-03-25 10:40
Thanks for reporting this. I think this could be a duplicate of #955

**Closed** 2018-03-25 13:33 UTC
