### ISSUE TITLE
[multilingual products] Allow admin to delete a language tab for one product

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-server#236] opened 2016-02-21 15:57 UTC
Also automatically delete language tabs that do not have any images or field values

**Comment by lucaa** [comment] 2017-02-16 21:05
This issue looks like a duplicate of issue #483 . Actually, it's the other way around, but that issue looks like more detailed :) , so I will close this one now.

**Closed by lucaa** 2017-02-16 21:05 UTC
Labels: admin tools, duplicate, multingual products, P3
