### ISSUE TITLE
Build failing because of rake

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#2506] opened 2019-10-30 09:48 UTC
``` 
Build system information
0.02s0.01s0.38s0.25s0.06s0.00s0.05s0.00s0.01s0.01s0.01s0.01s0.01s0.00s0.00s0.03s0.00s0.01s0.33s0.00s0.00s0.00s0.01s0.00s0.12s0.01s0.91s0.00s0.12s3.07s0.00s2.79s0.00s2.34s
docker_mtu
resolvconf
git.checkout
36.27s$ git clone --depth=50 https://github.com/openfoodfacts/openfoodfacts-server.git openfoodfacts/openfoodfacts-server
git.submodule
0.04s$ git submodule update --init --recursive
Setting environment variables from repository settings
$ export FOSSA_API_TOKEN=[secure]
rvm
0.79s$ rvm use default
ruby.versions
$ ruby --version
No Gemfile found, skipping bundle install
0.17s$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-2.5.3@global/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.5.3@global/bin/ruby_executable_hooks:24:in `eval'
/home/travis/.rvm/gems/ruby-2.5.3@global/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
The command "rake" exited with 1.
Done. Your build exited with 1.
```

**Comment by stephanegigandet** [comment] 2019-10-30 17:03
I can't figure that one out. Any idea @hangy ?

**Comment by stephanegigandet** [comment] 2019-10-31 13:39
Probably a syntax error in .travis.yml in fact:
https://github.com/travis-ci/travis-ci/issues/9150

**Comment by stephanegigandet** [comment] 2019-10-31 13:45
the online validator https://config.travis-ci.com/explore does not seem to work...

**Comment by hangy** [comment] 2019-10-31 20:09
I don't think it's related to a change in our repository. We most recently updated [,travis.yml](https://github.com/openfoodfacts/openfoodfacts-server/commits/master/.travis.yml) in ac3f2af75c0d023246ec390314f695e83a0c7f1e, and that build went well. Also, the build for the commit before that change 2ffcdad71dc36aacad32e101c0a87f602e111627 worked the same way as the build for the next push 269fd605e241126817f3e36098defe19c7a5c8e6 did: In both cases, Travis CI claimed the project language was Ruby, and it also ran `rvm use default`. For whatever reason, Travis first started executing the `ruby` command, and thus failing the build, at 1999d95c78147654744123817510b4c3355c855c.

I'll try with some different languages ...

**Comment by hangy** [comment] 2019-10-31 20:13
Actually, the last commit (at the time of writing) was built successfully in [my fork](https://travis-ci.com/hangy/openfoodfacts-server/builds/134418053) while failing on [this repo](https://travis-ci.org/openfoodfacts/openfoodfacts-server/builds/605549906?utm_source=github_status&utm_medium=notification). It might be a difference between travis-ci.com and travis-ci.org.

**Comment by VaiTon** [comment] 2019-11-01 10:28
Still not working, even after merging #2513.

**Comment by stephanegigandet** [comment] 2019-11-01 12:15
Seems to be caused by the slack notifications, removing them make the tests pass:
https://github.com/openfoodfacts/openfoodfacts-server/pull/2520

**Comment by stephanegigandet** [comment] 2019-11-01 12:34
OK I guess we can try to put back slack notifications at some point if we need them. Closing this bug.

**Closed by stephanegigandet** 2019-11-01 12:34 UTC
Labels: P1, bug, ci
