### ISSUE TITLE
Find cutting solution for this kind of ingredient lists

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1858] opened 2019-06-02 20:17 UTC
```Matières grasses 2,9 g Glucides 19,5 g Fibres alimentaires 1,3 g Protéines 3,8 g Sel 0,69 g```

**Comment by teolemon** [comment] 2019-06-02 20:18
if (Matières grasses XX g) then cut ?

**Comment by aleene** [comment] 2019-06-03 06:27
Find a regexp that cuts "Matières grasses..g...Glucides". Still dangerous, but better.

**Comment by stephanegigandet** [comment] 2019-06-03 06:45
For each cutting problem we want to solve, we need to make sure that the problem is common enough (e.g. that it will affect at least 100 products). Otherwise we introduce a lot of risk, especially when those things will be translated to hundreds of languages. We do not want hundreds of regular expressions.
I don't know how common this specific pattern is, but that's the thing: we first need lots of examples so that we find the best solution.

**Comment by stephanegigandet** [comment] 2020-01-25 18:44
Closing, please reopen if there are more examples.

**Closed by stephanegigandet** 2020-01-25 18:44 UTC
Labels: ingredient-list-cutting
