### ISSUE TITLE
Should be nice to have godchildren link

### ISSUE THREAD

**Issue by astrubel-zz** [openfoodfacts/openfoodfacts-server#156] opened 2015-08-17 11:37 UTC

**Comment by kyzh** [comment] 2015-08-17 20:16
Could you explain what you mean in a bit more details?

**Comment by kyzh** [comment] 2015-08-17 20:17
Or provide an example :)

**Comment by astrubel** [comment] 2015-08-18 07:23
Ok ;)

Some friends of me created an off account and I must retains their nickname to see and correct their contributions. In my opinion, the godfather is responsible for his godchildren. Maybe referrer and referee are best words that godfather and godchild..

I just want a link to specific contributors like "Products you added or edited".
A favorite contributor system should be enough (add and remove contributors) but I think a referrer system could be best. Where we could invite by email some friends to off.
This 2 systems can work together too.

Referrer: contributor1
Referees: contributor1, contributor2, ..
Favorites: contributor1, contributor2, ..

**Comment by teolemon** [comment] 2021-08-25 05:53
Duplicate of #40 
closing

**Closed by teolemon** 2021-08-25 05:53 UTC
Labels: open food hunt, gamification
