### ISSUE TITLE
Database message is shown as alert() when user is opening statistics page 

### ISSUE THREAD

**Issue by sashabrava** [openfoodfacts/openfoodfacts-server#2813] opened 2019-12-24 00:50 UTC
**Describe the bug**
If I open the page https://world.openfoodfacts.org/cgi/top_translators.pl, I can see an alert message "DataTables warning: table id=top_translators - Requested unknown parameter 'Translated (Words)' for row 335, column 1. For more information about this error, please see http://datatables.net/tn/4"

Seems like there is an issue with database request, but it makes sense to hide such type of messages at least to the console.log method on frontend (or better to log file on backend), so that it won't scare non-technical users.

**To Reproduce**
1. Go to https://world.openfoodfacts.org/cgi/top_translators.pl
2. See alert message, which might be fixed or overall hidden from user.

**Desktop:**
 - OS: Arch Linux
 - Browser: Chromium
 - Version: 79

**Comment by hangy** [comment] 2019-12-24 10:31
Thanks for the report! It's actually a duplicate of #2777, and is currently awaiting deployment.

**Closed by hangy** 2019-12-24 10:31 UTC
Labels: bug
