### ISSUE TITLE
Empty pages

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#310] opened 2016-05-21 23:48 UTC
http://world.openfoodfacts.org/4121

**Comment by hangy** [comment] 2016-05-22 11:15
I think this could be caused by MongoDB being inefficient when pagination is done with `skip`, according to [some](https://scalegrid.io/blog/fast-paging-with-mongodb/) [documentations](https://www.safaribooksonline.com/library/view/mongodb-the-definitive/9781449344795/ch04.html). Opening page 4121 worldwide comes down to a query like `db.off.find().sort({}).skip(82420).limit(20)`, which takes a really long time on my VM. I don't know how exactly MongoDB and the Perl driver behave in that case, but one plausible explanation for the empty pages might be that the query takes too long and is cancelled somehow, I think.

**Comment by stephanegigandet** [comment] 2019-06-05 19:58
I don't see any empty pages now. Can I close this?

**Closed** 2019-06-26 12:58 UTC
Labels: mongodb
